In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ulus.csv')
df.head()

,Улус;Администр. центр;Площадь,тыс.км2;Численность населения (2002 г.),чел;Расст до Якт наземным;Расст до Якт водным;Расст до Якт воздушным;городов респ;городов улусного;поселков;сел;наслегов
0,Абыйский;п. Белая Гора;69,4;4750;1950/2900;3243;1148;-;-;1;6;5,NaN
1,Алданский;г. Алдан;156,8;49346;534;-;470;-;2;4;13;3,NaN
2,Аллаиховский;п. Чокурдах;107,3;3421;2700;2830;1290;-;-;1;6;5,NaN
3,Амгинский;с. Амга;29,4;17251;201;1036;200;-;-;-;21;14,NaN
4,Анабарский;с. Саскылах;55,6;4024;2621;2835;1285;-;-;-;3;3,NaN

In [3]:
df = pd.read_csv('ulus.csv', sep=';')
df.head()

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950/2900,3243,1148,-,-,1,6.0,5.0
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0

In [4]:
df.dtypes

Улус                                      object
Администр. центр                          object
Площадь, тыс.км2                          object
Численность населения (2002  г.), чел    float64
Расст до Якт наземным                     object
Расст до Якт водным                       object
Расст до Якт воздушным                    object
городов респ                              object
городов улусного                          object
поселков                                  object
сел                                      float64
наслегов                                 float64
dtype: object

In [5]:
df.columns

Index(['Улус', 'Администр. центр', 'Площадь, тыс.км2',
       'Численность населения (2002  г.), чел', 'Расст до Якт наземным',
       'Расст до Якт водным', 'Расст до Якт воздушным', 'городов респ',
       'городов улусного', 'поселков', 'сел', 'наслегов'],
      dtype='object')

In [6]:
df[df.columns[2]]

0      69,4
1     156,8
2     107,3
3      29,4
4      55,6
5     223,6
6        42
7      67,8
8     137,4
9      55,2
10     45,6
11    140,2
12    107,8
13       77
14     11,7
15    165,8
16    104,6
17     11,9
18     98,9
19     87,1
20     52,4
21     92,3
22    160,8
23      318
24      NaN
25    125,2
26     57,8
27       19
28    135,8
29     18,3
30     95,3
31    120,3
32     24,7
33     12,6
34     52,3
35      3,6
Name: Площадь, тыс.км2, dtype: object

In [7]:
df['area']=df.replace

In [8]:
s='6,2'
s

'6,2'

In [9]:
s.replace(',','.')

'6.2'

In [10]:
def replace_comma(s):
    return s.replace(',','.') if type(s)==str else '0'

In [11]:
df['area']=df['area'].apply(replace_comma)

In [12]:
df['area']=df['area'].astype(float)

In [13]:
df.dtypes

Улус                                      object
Администр. центр                          object
Площадь, тыс.км2                          object
Численность населения (2002  г.), чел    float64
Расст до Якт наземным                     object
Расст до Якт водным                       object
Расст до Якт воздушным                    object
городов респ                              object
городов улусного                          object
поселков                                  object
сел                                      float64
наслегов                                 float64
area                                     float64
dtype: object

In [14]:
df.drop([24], inplace= True)

In [15]:
df

,Улус,Администр. центр,"Площадь, тыс.км2","Численность населения (2002 г.), чел",Расст до Якт наземным,Расст до Якт водным,Расст до Якт воздушным,городов респ,городов улусного,поселков,сел,наслегов,area
0,Абыйский,п. Белая Гора,"69,4",4750.0,1950/2900,3243,1148,-,-,1,6.0,5.0,0.0
1,Алданский,г. Алдан,"156,8",49346.0,534,-,470,-,2,4,13.0,3.0,0.0
2,Аллаиховский,п. Чокурдах,"107,3",3421.0,2700,2830,1290,-,-,1,6.0,5.0,0.0
3,Амгинский,с. Амга,"29,4",17251.0,201,1036,200,-,-,-,21.0,14.0,0.0
4,Анабарский,с. Саскылах,"55,6",4024.0,2621,2835,1285,-,-,-,3.0,3.0,0.0
5,Булунский,п. Тикси,"223,6",9775.0,1694,1703,1270,-,-,1,9.0,8.0,0.0
6,Верхневилюйский,с. Верхневилюйск,42,21383.0,677,847,610,-,-,-,29.0,21.0,0.0
7,Верхнеколымский,п. Зырянка,"67,8",5653.0,2440,4282,1255,-,-,1,5.0,5.0,0.0
8,Верхоянский,п. Батагай,"137,4",13666.0,1400,2785,705,-,1,2,26.0,14.0,0.0
9,Вилюйский,г. Вилюйск,"55,2",25696.0,592,739,535,-,1,1,25.0,19.0,0.0
10,Горный,с. Бердигестях,"45,6",11422.0,184,-,150,-,-,-,16.0,9.0,0.0
11,Жиганский эвенкийский национальный,с. Жиганск,"140,2",4312.0,754,764,610,-,-,-,5.0,4.0,0.0
12,Кобяйский,п. Сангар,"107,8",14178.0,334/527,330,240,-,-,1,22.0,11.0,0.0
13,Ленский,г. Ленск,77,38669.0,1070/1387,1027,840,-,1,2,16.0,8.0,0.0
14,Мегино-Кангаласский,с. Майя,"11,7",32288.0,52,-,60,-,-,1,35.0,29.0,0.0
15,Мирнинский,г. Мирный,"165,8",86013.0,1207,-,820,1,1,4,8.0,3.0,0.0
16,Момский,с. Хонуу,"104,6",4699.0,2000,3774,1125,-,-,-,7.0,6.0,0.0
17,Намский,с. Намцы,"11,9",21454.0,84,96,-,-,-,-,24.0,18.0,0.0
18,Нерюнгринский*,г. Нерюнгри,"98,9",89796.0,818,-,670,1,-,6,2.0,1.0,0.0
19,Нижнеколымский,п. Черский,"87,1",5932.0,3189,3421,1920,-,-,1,12.0,3.0,0.0
20,Нюрбинский*,г. Нюрба,"52,4",25858.0,812,977,600,1,-,-,23.0,18.0,0.0
21,Оймяконский,п. Усть-Нера,"92,3",14670.0,1040,-,865,-,-,2,13.0,5.0,0.0
22,Олекминский,г. Олекминск,"160,8",27563.0,651,620,530,-,1,1,52.0,21.0,0.0
23,Оленекский эвенкийский национальный,с. Оленек,318,4091.0,2026,3989,1105,-,-,-,4.0,4.0,0.0
25,Среднеколымский,г. Среднеколымск,"125,2",8353.0,2664,3940,1485,-,1,-,14.0,9.0,0.0
26,Сунтарский,с. Сунтар,"57,8",25485.0,985,1151,730,-,-,-,39.0,26.0,0.0
27,Таттинский,с. Ытык-Кюёль,19,16601.0,256,-,255,-,-,-,15.0,14.0,0.0
28,Томпонский,п. Хандыга,"135,8",15275.0,449,642,370,-,-,2,12.0,7.0,0.0
29,Усть-Алданский,с. Борогонцы,"18,3",22372.0,127,-,110,-,-,-,35.0,21.0,0.0
30,Усть-Майский,п. Усть-Мая,"95,3",11568.0,382,-,310,-,-,6,10.0,5.0,0.0
31,Усть-Янский,п. Депутатский,"120,3",10009.0,2068,-,1025,-,-,3,7.0,7.0,0.0
32,Хангаласский*,г. Покровск,"24,7",35201.0,74,88,75,1,-,1,27.0,16.0,0.0
33,Чурапчинский,с. Чурапча,"12,6",19466.0,182,-,180,-,-,-,30.0,17.0,0.0
34,Эвено-Бытантайский национальный,с. Батагай-Алыта,"52,3",2761.0,1687,-,850,-,-,-,4.0,3.0,0.0
35,Якутск,г. Якутск,"3,6",246279.0,-,-,-,1,-,1,11.0,2.0,0.0

# ЗАДАНИЕ 3

In [16]:
df['density']=df['Численность населения\xa0(2002\xa0 г.), чел']/(1000*df['area'])

In [17]:
df['Улус'][df['density'].idxmin()]

'Абыйский'

# ЗАДАНИЕ 4

In [18]:
df['Расст до Якт воздушным'][17]=84

c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [19]:
df['Расст до Якт воздушным'][35]=1

c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [20]:
df['Расст до Якт наземным'][0]=2900

c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [21]:
df['Расст до Якт наземным'][12]=527

c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [22]:
df['Расст до Якт наземным'][13]=1387

c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
df['Расст до Якт наземным'][35]=0

c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [24]:
df['Расст до Якт наземным']=df['Расст до Якт наземным'].astype(int)

In [25]:
df['Расст до Якт воздушным']=df['Расст до Якт воздушным'].astype(int)

In [26]:
df['qwerty']=df['Расст до Якт наземным']/df['Расст до Якт воздушным']

In [27]:
df['Улус'][df['qwerty'].idxmax()]

'Абыйский'

In [28]:
df['qwerty']

0     2.526132
1     1.136170
2     2.093023
3     1.005000
4     2.039689
5     1.333858
6     1.109836
7     1.944223
8     1.985816
9     1.106542
10    1.226667
11    1.236066
12    2.195833
13    1.651190
14    0.866667
15    1.471951
16    1.777778
17    1.000000
18    1.220896
19    1.660937
20    1.353333
21    1.202312
22    1.228302
23    1.833484
25    1.793939
26    1.349315
27    1.003922
28    1.213514
29    1.154545
30    1.232258
31    2.017561
32    0.986667
33    1.011111
34    1.984706
35    0.000000
Name: qwerty, dtype: float64